[build]
  command = "npm run build"
  functions = "functions"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 8888
  publish = "dist"
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"
